name: layout_basics1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Firestore
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

  # Payment & Stripe Integration
  flutter_stripe: ^11.3.0
  flutter_stripe_web: ^6.3.0

  # UI & Icons
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.5

  # Other Utilities
  path_provider: ^2.0.14
  json_editor_flutter: ^1.1.0
  focusable_control_builder: ^1.0.0
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  carousel_slider: ^4.2.1   # Carousel for featured products, etc.
  intl: ^0.20.1 # Add intl for date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
