// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBldsHBhEzYUnhN5FHn1otjbgQNf4dvZU',
    appId: '1:666996116910:web:3bcb162b54533da7e44c3f',
    messagingSenderId: '666996116910',
    projectId: 'ecommerce2-f821b',
    authDomain: 'ecommerce2-f821b.firebaseapp.com',
    databaseURL: 'https://ecommerce2-f821b-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce2-f821b.firebasestorage.app',
    measurementId: 'G-FHN6NQB0ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4fhFXYhAbZGgpyMKrQ4ECIYit-XGev8U',
    appId: '1:666996116910:android:95e076993ab824e9e44c3f',
    messagingSenderId: '666996116910',
    projectId: 'ecommerce2-f821b',
    databaseURL: 'https://ecommerce2-f821b-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce2-f821b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_SXbuZsKxv1uJJL1U5QV3Rh2sww5Uklk',
    appId: '1:666996116910:ios:87a69a35cdee806ae44c3f',
    messagingSenderId: '666996116910',
    projectId: 'ecommerce2-f821b',
    databaseURL: 'https://ecommerce2-f821b-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce2-f821b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_SXbuZsKxv1uJJL1U5QV3Rh2sww5Uklk',
    appId: '1:666996116910:ios:87a69a35cdee806ae44c3f',
    messagingSenderId: '666996116910',
    projectId: 'ecommerce2-f821b',
    databaseURL: 'https://ecommerce2-f821b-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce2-f821b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBldsHBhEzYUnhN5FHn1otjbgQNf4dvZU',
    appId: '1:666996116910:web:86d99d7856bead21e44c3f',
    messagingSenderId: '666996116910',
    projectId: 'ecommerce2-f821b',
    authDomain: 'ecommerce2-f821b.firebaseapp.com',
    databaseURL: 'https://ecommerce2-f821b-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce2-f821b.firebasestorage.app',
    measurementId: 'G-176DECBLZ2',
  );
}
